version: '3.8'

services:
  # Nombre del servicio del microservicio
  ep3-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: EP3_container
    # Mapeo de puertos: Puerto_Host:Puerto_Contenedor
    ports:
      - "8080:8080"
    # Variables de entorno simuladas para el entorno de desarrollo/testing
    environment:
      - NODE_ENV=production
      - PORT=8080
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - devops-network
    restart: always

  # Prometheus service to collect metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - devops-network
    restart: always

  # Grafana service for dashboards visualization
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana_container
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - devops-network
    depends_on:
      - prometheus
    restart: always

networks:
  devops-network:
    driver: bridge